server.port=8080
spring.application.name=RentalService

# Docker Compose configuration
# firstname.service.url=http://firstname-service/index.php

# Kubernetes configuration
firstname.service.url=http://firstname-service.default.svc.cluster.local:80/index.php